---
title: ""
date: ""
---

```{r setup, include=FALSE}
setwd("C:/Users/crish/OneDrive/Documents/D4C")

library(xlsx)
coordenadas <- read.xlsx("coordenadas.xlsx", 1)
mexico_city  <- read.xlsx("coordenadas.xlsx", 2)

```

### Mapa con coordenadas seleccionadas

```{r, message==FALSE, warning=FALSE, echo=FALSE}

library(leaflet)
library(htmltools)

m1<- leaflet(coordenadas)%>%  
  addTiles()%>%
  addPolygons(coordenadas, lat=~cdmxlat, lng=~cdmxlng, fillOpacity = 0) %>%
  addCircleMarkers(lat=~latitud, lng=~longitude, popup=~htmltools::htmlEscape(nombre), weight=0, radius=6, 
                   fillColor = ~color, fillOpacity = 0.6)
m1
```



###Versión 2 - con clusters

```{r, warning=FALSE, echo=FALSE}

m2<- leaflet(coordenadas)%>%  
  addTiles()%>%
  addPolygons(coordenadas, lat=~cdmxlat, lng=~cdmxlng, fillOpacity = 0) %>%
  addCircleMarkers(lat=~latitud, lng=~longitude, popup=~htmltools::htmlEscape(nombre), weight=0, radius=6, 
                   fillColor = ~color, fillOpacity = 0.6, clusterOptions = markerClusterOptions())

m2  
```
```

